name: flutter_app_name_all
description: A package that makes it easy to set your flutter app launcher name.
version: 0.1.1+packagename
maintainer: Frankie Primerano (@f-prime)
homepage: https://github.com/f-prime/flutter_app_name_all

dependencies:
  rename: ^2.1.1
  xml: ^6.3.0 # 6.4.0 requires collection 1.18.0 which conflics with a bunch of stuff
  yaml: ^3.1.2

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  dart_lintz: ^1.2.0
  test: ^1.24.6

flutter_app_name_all:
  name: "Flutter App Name"
